image: docker:latest

services:
  - docker:dind

variables:
  KUBE_CONTEXT: "your-kube-context"  # Substitua pelo seu contexto Kubernetes
  KUBE_NAMESPACE: "default"            # Substitua pelo seu namespace se necessário
  DOCKER_IMAGE: "nginx"  # Substitua pelo seu nome de usuário e imagem

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache bash curl

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE:latest .
    - echo "Pushing Docker image..."
    - docker push $DOCKER_IMAGE:latest

deploy:
  stage: deploy
  script:
    - echo "Setting up kubectl..."
    - apk add --no-cache kubectl
    - echo "$KUBE_CONFIG" | base64 -d > /root/.kube/config
    - kubectl config use-context $KUBE_CONTEXT
    - echo "Deploying to Kubernetes..."
    - kubectl apply -f k8s/  # Certifique-se de que seus arquivos YAML estejam na pasta 'k8s/'
    - kubectl rollout status deployment/example-app  # Aguarde a conclusão do deployment
  environment:
    name: production
    url: http://example.com  # Substitua pela URL do seu serviço
  only:
    - main  # Ou a branch que você deseja implantar
